jwt:
  iss: auth-playground
  secretAccessKey: 64461f01e1af406da538b9c48d801ce59142452199ff112fb5404c8e7e98e3ff
  accessTokenExpire: 300000
  refreshTokenExpire: 604800000

spring:
  application:
    name: auth-playground

  h2:
    console:
      enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/auth-playground
    username: sa
    password:

  redis:
    host: localhost
    port: 6379

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
