jwt:
  secret-key: your-secret-key-which-should-be-very-secure
  issuer: auth.playground.com
  access-token-expiration: 3_600_000            # 1시간 (1,000 * 60 * 60)
  refresh-token-expiration: 1_209_600_000       # 14일  (1,000 * 60 * 60 * 24 * 14)

spring:
  application:
    name: auth-playground

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

  data:
    redis:
      host: localhost
      port: 6379

aes:
  secret-key: 1234567890abcdef
